package alipay.mapper;

import alipay.bean.TransformOrderDetails;
import alipay.bean.TransformOrderDetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TransformOrderDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transform_order_details
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    int countByExample(TransformOrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transform_order_details
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    int deleteByExample(TransformOrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transform_order_details
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transform_order_details
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    int insert(TransformOrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transform_order_details
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    int insertSelective(TransformOrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transform_order_details
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    List<TransformOrderDetails> selectByExample(TransformOrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transform_order_details
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    TransformOrderDetails selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transform_order_details
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    int updateByExampleSelective(@Param("record") TransformOrderDetails record, @Param("example") TransformOrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transform_order_details
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    int updateByExample(@Param("record") TransformOrderDetails record, @Param("example") TransformOrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transform_order_details
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    int updateByPrimaryKeySelective(TransformOrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transform_order_details
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    int updateByPrimaryKey(TransformOrderDetails record);
}