package orderService.bean;

import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.id
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.user_id
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.title
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.sub_type
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private String subType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.use_time
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private String useTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.specs
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private String specs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.price
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.total_price
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private String totalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.total_amount
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private String totalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.create_time
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_id
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_status
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private Integer orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.item_id
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private String itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.pay_order_id
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private String payOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.payment_order_id
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private String paymentOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.actual_amount
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private String actualAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_type
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private Integer orderType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.id
     *
     * @return the value of t_order.id
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.id
     *
     * @param id the value for t_order.id
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.user_id
     *
     * @return the value of t_order.user_id
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.user_id
     *
     * @param userId the value for t_order.user_id
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.title
     *
     * @return the value of t_order.title
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.title
     *
     * @param title the value for t_order.title
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.sub_type
     *
     * @return the value of t_order.sub_type
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    public String getSubType() {
        return subType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.sub_type
     *
     * @param subType the value for t_order.sub_type
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    public void setSubType(String subType) {
        this.subType = subType == null ? null : subType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.use_time
     *
     * @return the value of t_order.use_time
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    public String getUseTime() {
        return useTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.use_time
     *
     * @param useTime the value for t_order.use_time
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    public void setUseTime(String useTime) {
        this.useTime = useTime == null ? null : useTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.specs
     *
     * @return the value of t_order.specs
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    public String getSpecs() {
        return specs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.specs
     *
     * @param specs the value for t_order.specs
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    public void setSpecs(String specs) {
        this.specs = specs == null ? null : specs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.price
     *
     * @return the value of t_order.price
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.price
     *
     * @param price the value for t_order.price
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.total_price
     *
     * @return the value of t_order.total_price
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    public String getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.total_price
     *
     * @param totalPrice the value for t_order.total_price
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    public void setTotalPrice(String totalPrice) {
        this.totalPrice = totalPrice == null ? null : totalPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.total_amount
     *
     * @return the value of t_order.total_amount
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    public String getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.total_amount
     *
     * @param totalAmount the value for t_order.total_amount
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    public void setTotalAmount(String totalAmount) {
        this.totalAmount = totalAmount == null ? null : totalAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.create_time
     *
     * @return the value of t_order.create_time
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.create_time
     *
     * @param createTime the value for t_order.create_time
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_id
     *
     * @return the value of t_order.order_id
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_id
     *
     * @param orderId the value for t_order.order_id
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_status
     *
     * @return the value of t_order.order_status
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_status
     *
     * @param orderStatus the value for t_order.order_status
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.item_id
     *
     * @return the value of t_order.item_id
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.item_id
     *
     * @param itemId the value for t_order.item_id
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    public void setItemId(String itemId) {
        this.itemId = itemId == null ? null : itemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.pay_order_id
     *
     * @return the value of t_order.pay_order_id
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    public String getPayOrderId() {
        return payOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.pay_order_id
     *
     * @param payOrderId the value for t_order.pay_order_id
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    public void setPayOrderId(String payOrderId) {
        this.payOrderId = payOrderId == null ? null : payOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.payment_order_id
     *
     * @return the value of t_order.payment_order_id
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    public String getPaymentOrderId() {
        return paymentOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.payment_order_id
     *
     * @param paymentOrderId the value for t_order.payment_order_id
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    public void setPaymentOrderId(String paymentOrderId) {
        this.paymentOrderId = paymentOrderId == null ? null : paymentOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.actual_amount
     *
     * @return the value of t_order.actual_amount
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    public String getActualAmount() {
        return actualAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.actual_amount
     *
     * @param actualAmount the value for t_order.actual_amount
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    public void setActualAmount(String actualAmount) {
        this.actualAmount = actualAmount == null ? null : actualAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_type
     *
     * @return the value of t_order.order_type
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    public Integer getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_type
     *
     * @param orderType the value for t_order.order_type
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }
}