package orderService.dto;

import lombok.Data;

import java.util.Date;

/**
 * @author xiaohao
 * @version 1.0
 * @date 2022/10/24 22:57
 */
@Data
public class DataReceiveOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.id
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.user_id
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.title
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.sub_type
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private String subType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.use_time
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private String useTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.specs
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private String specs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.price
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.total_price
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private String totalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.total_amount
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private String totalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.create_time
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_id
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_status
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private Integer orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.item_id
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private String itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.pay_order_id
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private String payOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.payment_order_id
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private String paymentOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.actual_amount
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private String actualAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_type
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private Integer orderType;
}
