package orderService.dto;

import lombok.Data;

import java.util.Date;

/**
 * @author xiaohao
 * @version 1.0
 * @date 2022/10/25 20:12
 */
@Data
public class OrderRequest {


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.user_id
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private String userId;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.create_time
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private String createTimes[];

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_id
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_status
     *
     * @mbggenerated Mon Oct 24 22:52:13 GMT+08:00 2022
     */
    private Integer orderStatus;





}
