package alipay.bean;

import lombok.Data;

import java.util.Date;
/**
 * @author root
 */
@Data
public class PaymentOrderDetails {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_order_details.id
     *
     * @mbggenerated Sat Oct 22 21:13:55 GMT+08:00 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_order_details.user_id
     *
     * @mbggenerated Sat Oct 22 21:13:55 GMT+08:00 2022
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_order_details.order_id
     * 支付订单号
     *
     * @mbggenerated Sat Oct 22 21:13:55 GMT+08:00 2022
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_order_details.payment_id
     * 支付宝返回的商户订单号
     *
     * @mbggenerated Sat Oct 22 21:13:55 GMT+08:00 2022
     */
    private String paymentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_order_details.notify_url
     *
     * @mbggenerated Sat Oct 22 21:13:55 GMT+08:00 2022
     */
    private String notifyUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_order_details.order_status
     *
     * @mbggenerated Sat Oct 22 21:13:55 GMT+08:00 2022
     */
    private Integer orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_order_details.pay_amount
     *
     * @mbggenerated Sat Oct 22 21:13:55 GMT+08:00 2022
     */
    private Integer payAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_order_details.order_subject
     *
     * @mbggenerated Sat Oct 22 21:13:55 GMT+08:00 2022
     */
    private String orderSubject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_order_details.actual_amount
     *
     * @mbggenerated Sat Oct 22 21:13:55 GMT+08:00 2022
     */
    private Integer actualAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_order_details.create_time
     *
     * @mbggenerated Sat Oct 22 21:13:55 GMT+08:00 2022
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_order_details.update_time
     *
     * @mbggenerated Sat Oct 22 21:13:55 GMT+08:00 2022
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_order_details.id
     *
     * @return the value of payment_order_details.id
     *
     * @mbggenerated Sat Oct 22 21:13:55 GMT+08:00 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_order_details.id
     *
     * @param id the value for payment_order_details.id
     *
     * @mbggenerated Sat Oct 22 21:13:55 GMT+08:00 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_order_details.user_id
     *
     * @return the value of payment_order_details.user_id
     *
     * @mbggenerated Sat Oct 22 21:13:55 GMT+08:00 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_order_details.user_id
     *
     * @param userId the value for payment_order_details.user_id
     *
     * @mbggenerated Sat Oct 22 21:13:55 GMT+08:00 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_order_details.order_id
     *
     * @return the value of payment_order_details.order_id
     *
     * @mbggenerated Sat Oct 22 21:13:55 GMT+08:00 2022
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_order_details.order_id
     *
     * @param orderId the value for payment_order_details.order_id
     *
     * @mbggenerated Sat Oct 22 21:13:55 GMT+08:00 2022
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_order_details.payment_id
     *
     * @return the value of payment_order_details.payment_id
     *
     * @mbggenerated Sat Oct 22 21:13:55 GMT+08:00 2022
     */
    public String getPaymentId() {
        return paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_order_details.payment_id
     *
     * @param paymentId the value for payment_order_details.payment_id
     *
     * @mbggenerated Sat Oct 22 21:13:55 GMT+08:00 2022
     */
    public void setPaymentId(String paymentId) {
        this.paymentId = paymentId == null ? null : paymentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_order_details.notify_url
     *
     * @return the value of payment_order_details.notify_url
     *
     * @mbggenerated Sat Oct 22 21:13:55 GMT+08:00 2022
     */
    public String getNotifyUrl() {
        return notifyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_order_details.notify_url
     *
     * @param notifyUrl the value for payment_order_details.notify_url
     *
     * @mbggenerated Sat Oct 22 21:13:55 GMT+08:00 2022
     */
    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl == null ? null : notifyUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_order_details.order_status
     *
     * @return the value of payment_order_details.order_status
     *
     * @mbggenerated Sat Oct 22 21:13:55 GMT+08:00 2022
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_order_details.order_status
     *
     * @param orderStatus the value for payment_order_details.order_status
     *
     * @mbggenerated Sat Oct 22 21:13:55 GMT+08:00 2022
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_order_details.pay_amount
     *
     * @return the value of payment_order_details.pay_amount
     *
     * @mbggenerated Sat Oct 22 21:13:55 GMT+08:00 2022
     */
    public Integer getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_order_details.pay_amount
     *
     * @param payAmount the value for payment_order_details.pay_amount
     *
     * @mbggenerated Sat Oct 22 21:13:55 GMT+08:00 2022
     */
    public void setPayAmount(Integer payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_order_details.order_subject
     *
     * @return the value of payment_order_details.order_subject
     *
     * @mbggenerated Sat Oct 22 21:13:55 GMT+08:00 2022
     */
    public String getOrderSubject() {
        return orderSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_order_details.order_subject
     *
     * @param orderSubject the value for payment_order_details.order_subject
     *
     * @mbggenerated Sat Oct 22 21:13:55 GMT+08:00 2022
     */
    public void setOrderSubject(String orderSubject) {
        this.orderSubject = orderSubject == null ? null : orderSubject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_order_details.actual_amount
     *
     * @return the value of payment_order_details.actual_amount
     *
     * @mbggenerated Sat Oct 22 21:13:55 GMT+08:00 2022
     */
    public Integer getActualAmount() {
        return actualAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_order_details.actual_amount
     *
     * @param actualAmount the value for payment_order_details.actual_amount
     *
     * @mbggenerated Sat Oct 22 21:13:55 GMT+08:00 2022
     */
    public void setActualAmount(Integer actualAmount) {
        this.actualAmount = actualAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_order_details.create_time
     *
     * @return the value of payment_order_details.create_time
     *
     * @mbggenerated Sat Oct 22 21:13:55 GMT+08:00 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_order_details.create_time
     *
     * @param createTime the value for payment_order_details.create_time
     *
     * @mbggenerated Sat Oct 22 21:13:55 GMT+08:00 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_order_details.update_time
     *
     * @return the value of payment_order_details.update_time
     *
     * @mbggenerated Sat Oct 22 21:13:55 GMT+08:00 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_order_details.update_time
     *
     * @param updateTime the value for payment_order_details.update_time
     *
     * @mbggenerated Sat Oct 22 21:13:55 GMT+08:00 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}