package alipay.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TransformOrderDetailsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table transform_order_details
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table transform_order_details
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table transform_order_details
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transform_order_details
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    public TransformOrderDetailsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transform_order_details
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transform_order_details
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transform_order_details
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transform_order_details
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transform_order_details
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transform_order_details
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transform_order_details
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transform_order_details
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transform_order_details
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transform_order_details
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table transform_order_details
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andAliIdIsNull() {
            addCriterion("ali_id is null");
            return (Criteria) this;
        }

        public Criteria andAliIdIsNotNull() {
            addCriterion("ali_id is not null");
            return (Criteria) this;
        }

        public Criteria andAliIdEqualTo(String value) {
            addCriterion("ali_id =", value, "aliId");
            return (Criteria) this;
        }

        public Criteria andAliIdNotEqualTo(String value) {
            addCriterion("ali_id <>", value, "aliId");
            return (Criteria) this;
        }

        public Criteria andAliIdGreaterThan(String value) {
            addCriterion("ali_id >", value, "aliId");
            return (Criteria) this;
        }

        public Criteria andAliIdGreaterThanOrEqualTo(String value) {
            addCriterion("ali_id >=", value, "aliId");
            return (Criteria) this;
        }

        public Criteria andAliIdLessThan(String value) {
            addCriterion("ali_id <", value, "aliId");
            return (Criteria) this;
        }

        public Criteria andAliIdLessThanOrEqualTo(String value) {
            addCriterion("ali_id <=", value, "aliId");
            return (Criteria) this;
        }

        public Criteria andAliIdLike(String value) {
            addCriterion("ali_id like", value, "aliId");
            return (Criteria) this;
        }

        public Criteria andAliIdNotLike(String value) {
            addCriterion("ali_id not like", value, "aliId");
            return (Criteria) this;
        }

        public Criteria andAliIdIn(List<String> values) {
            addCriterion("ali_id in", values, "aliId");
            return (Criteria) this;
        }

        public Criteria andAliIdNotIn(List<String> values) {
            addCriterion("ali_id not in", values, "aliId");
            return (Criteria) this;
        }

        public Criteria andAliIdBetween(String value1, String value2) {
            addCriterion("ali_id between", value1, value2, "aliId");
            return (Criteria) this;
        }

        public Criteria andAliIdNotBetween(String value1, String value2) {
            addCriterion("ali_id not between", value1, value2, "aliId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("order_id like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("order_id not like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andPaymentIdIsNull() {
            addCriterion("payment_id is null");
            return (Criteria) this;
        }

        public Criteria andPaymentIdIsNotNull() {
            addCriterion("payment_id is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentIdEqualTo(String value) {
            addCriterion("payment_id =", value, "paymentId");
            return (Criteria) this;
        }

        public Criteria andPaymentIdNotEqualTo(String value) {
            addCriterion("payment_id <>", value, "paymentId");
            return (Criteria) this;
        }

        public Criteria andPaymentIdGreaterThan(String value) {
            addCriterion("payment_id >", value, "paymentId");
            return (Criteria) this;
        }

        public Criteria andPaymentIdGreaterThanOrEqualTo(String value) {
            addCriterion("payment_id >=", value, "paymentId");
            return (Criteria) this;
        }

        public Criteria andPaymentIdLessThan(String value) {
            addCriterion("payment_id <", value, "paymentId");
            return (Criteria) this;
        }

        public Criteria andPaymentIdLessThanOrEqualTo(String value) {
            addCriterion("payment_id <=", value, "paymentId");
            return (Criteria) this;
        }

        public Criteria andPaymentIdLike(String value) {
            addCriterion("payment_id like", value, "paymentId");
            return (Criteria) this;
        }

        public Criteria andPaymentIdNotLike(String value) {
            addCriterion("payment_id not like", value, "paymentId");
            return (Criteria) this;
        }

        public Criteria andPaymentIdIn(List<String> values) {
            addCriterion("payment_id in", values, "paymentId");
            return (Criteria) this;
        }

        public Criteria andPaymentIdNotIn(List<String> values) {
            addCriterion("payment_id not in", values, "paymentId");
            return (Criteria) this;
        }

        public Criteria andPaymentIdBetween(String value1, String value2) {
            addCriterion("payment_id between", value1, value2, "paymentId");
            return (Criteria) this;
        }

        public Criteria andPaymentIdNotBetween(String value1, String value2) {
            addCriterion("payment_id not between", value1, value2, "paymentId");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIsNull() {
            addCriterion("order_status is null");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIsNotNull() {
            addCriterion("order_status is not null");
            return (Criteria) this;
        }

        public Criteria andOrderStatusEqualTo(Integer value) {
            addCriterion("order_status =", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotEqualTo(Integer value) {
            addCriterion("order_status <>", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusGreaterThan(Integer value) {
            addCriterion("order_status >", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_status >=", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusLessThan(Integer value) {
            addCriterion("order_status <", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusLessThanOrEqualTo(Integer value) {
            addCriterion("order_status <=", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIn(List<Integer> values) {
            addCriterion("order_status in", values, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotIn(List<Integer> values) {
            addCriterion("order_status not in", values, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusBetween(Integer value1, Integer value2) {
            addCriterion("order_status between", value1, value2, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("order_status not between", value1, value2, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andTransformAmountIsNull() {
            addCriterion("transform_amount is null");
            return (Criteria) this;
        }

        public Criteria andTransformAmountIsNotNull() {
            addCriterion("transform_amount is not null");
            return (Criteria) this;
        }

        public Criteria andTransformAmountEqualTo(Integer value) {
            addCriterion("transform_amount =", value, "transformAmount");
            return (Criteria) this;
        }

        public Criteria andTransformAmountNotEqualTo(Integer value) {
            addCriterion("transform_amount <>", value, "transformAmount");
            return (Criteria) this;
        }

        public Criteria andTransformAmountGreaterThan(Integer value) {
            addCriterion("transform_amount >", value, "transformAmount");
            return (Criteria) this;
        }

        public Criteria andTransformAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("transform_amount >=", value, "transformAmount");
            return (Criteria) this;
        }

        public Criteria andTransformAmountLessThan(Integer value) {
            addCriterion("transform_amount <", value, "transformAmount");
            return (Criteria) this;
        }

        public Criteria andTransformAmountLessThanOrEqualTo(Integer value) {
            addCriterion("transform_amount <=", value, "transformAmount");
            return (Criteria) this;
        }

        public Criteria andTransformAmountIn(List<Integer> values) {
            addCriterion("transform_amount in", values, "transformAmount");
            return (Criteria) this;
        }

        public Criteria andTransformAmountNotIn(List<Integer> values) {
            addCriterion("transform_amount not in", values, "transformAmount");
            return (Criteria) this;
        }

        public Criteria andTransformAmountBetween(Integer value1, Integer value2) {
            addCriterion("transform_amount between", value1, value2, "transformAmount");
            return (Criteria) this;
        }

        public Criteria andTransformAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("transform_amount not between", value1, value2, "transformAmount");
            return (Criteria) this;
        }

        public Criteria andOrderSubjectIsNull() {
            addCriterion("order_subject is null");
            return (Criteria) this;
        }

        public Criteria andOrderSubjectIsNotNull() {
            addCriterion("order_subject is not null");
            return (Criteria) this;
        }

        public Criteria andOrderSubjectEqualTo(String value) {
            addCriterion("order_subject =", value, "orderSubject");
            return (Criteria) this;
        }

        public Criteria andOrderSubjectNotEqualTo(String value) {
            addCriterion("order_subject <>", value, "orderSubject");
            return (Criteria) this;
        }

        public Criteria andOrderSubjectGreaterThan(String value) {
            addCriterion("order_subject >", value, "orderSubject");
            return (Criteria) this;
        }

        public Criteria andOrderSubjectGreaterThanOrEqualTo(String value) {
            addCriterion("order_subject >=", value, "orderSubject");
            return (Criteria) this;
        }

        public Criteria andOrderSubjectLessThan(String value) {
            addCriterion("order_subject <", value, "orderSubject");
            return (Criteria) this;
        }

        public Criteria andOrderSubjectLessThanOrEqualTo(String value) {
            addCriterion("order_subject <=", value, "orderSubject");
            return (Criteria) this;
        }

        public Criteria andOrderSubjectLike(String value) {
            addCriterion("order_subject like", value, "orderSubject");
            return (Criteria) this;
        }

        public Criteria andOrderSubjectNotLike(String value) {
            addCriterion("order_subject not like", value, "orderSubject");
            return (Criteria) this;
        }

        public Criteria andOrderSubjectIn(List<String> values) {
            addCriterion("order_subject in", values, "orderSubject");
            return (Criteria) this;
        }

        public Criteria andOrderSubjectNotIn(List<String> values) {
            addCriterion("order_subject not in", values, "orderSubject");
            return (Criteria) this;
        }

        public Criteria andOrderSubjectBetween(String value1, String value2) {
            addCriterion("order_subject between", value1, value2, "orderSubject");
            return (Criteria) this;
        }

        public Criteria andOrderSubjectNotBetween(String value1, String value2) {
            addCriterion("order_subject not between", value1, value2, "orderSubject");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andAliNameIsNull() {
            addCriterion("ali_name is null");
            return (Criteria) this;
        }

        public Criteria andAliNameIsNotNull() {
            addCriterion("ali_name is not null");
            return (Criteria) this;
        }

        public Criteria andAliNameEqualTo(String value) {
            addCriterion("ali_name =", value, "aliName");
            return (Criteria) this;
        }

        public Criteria andAliNameNotEqualTo(String value) {
            addCriterion("ali_name <>", value, "aliName");
            return (Criteria) this;
        }

        public Criteria andAliNameGreaterThan(String value) {
            addCriterion("ali_name >", value, "aliName");
            return (Criteria) this;
        }

        public Criteria andAliNameGreaterThanOrEqualTo(String value) {
            addCriterion("ali_name >=", value, "aliName");
            return (Criteria) this;
        }

        public Criteria andAliNameLessThan(String value) {
            addCriterion("ali_name <", value, "aliName");
            return (Criteria) this;
        }

        public Criteria andAliNameLessThanOrEqualTo(String value) {
            addCriterion("ali_name <=", value, "aliName");
            return (Criteria) this;
        }

        public Criteria andAliNameLike(String value) {
            addCriterion("ali_name like", value, "aliName");
            return (Criteria) this;
        }

        public Criteria andAliNameNotLike(String value) {
            addCriterion("ali_name not like", value, "aliName");
            return (Criteria) this;
        }

        public Criteria andAliNameIn(List<String> values) {
            addCriterion("ali_name in", values, "aliName");
            return (Criteria) this;
        }

        public Criteria andAliNameNotIn(List<String> values) {
            addCriterion("ali_name not in", values, "aliName");
            return (Criteria) this;
        }

        public Criteria andAliNameBetween(String value1, String value2) {
            addCriterion("ali_name between", value1, value2, "aliName");
            return (Criteria) this;
        }

        public Criteria andAliNameNotBetween(String value1, String value2) {
            addCriterion("ali_name not between", value1, value2, "aliName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table transform_order_details
     *
     * @mbggenerated do_not_delete_during_merge Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table transform_order_details
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}