package alipay.bean;

import java.util.Date;

public class TransformOrderDetails {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transform_order_details.id
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transform_order_details.user_id
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transform_order_details.ali_id
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    private String aliId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transform_order_details.order_id
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transform_order_details.payment_id
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    private String paymentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transform_order_details.order_status
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    private Integer orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transform_order_details.transform_amount
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    private Integer transformAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transform_order_details.order_subject
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    private String orderSubject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transform_order_details.create_time
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transform_order_details.update_time
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transform_order_details.ali_name
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    private String aliName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transform_order_details.id
     *
     * @return the value of transform_order_details.id
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transform_order_details.id
     *
     * @param id the value for transform_order_details.id
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transform_order_details.user_id
     *
     * @return the value of transform_order_details.user_id
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transform_order_details.user_id
     *
     * @param userId the value for transform_order_details.user_id
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transform_order_details.ali_id
     *
     * @return the value of transform_order_details.ali_id
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    public String getAliId() {
        return aliId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transform_order_details.ali_id
     *
     * @param aliId the value for transform_order_details.ali_id
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    public void setAliId(String aliId) {
        this.aliId = aliId == null ? null : aliId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transform_order_details.order_id
     *
     * @return the value of transform_order_details.order_id
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transform_order_details.order_id
     *
     * @param orderId the value for transform_order_details.order_id
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transform_order_details.payment_id
     *
     * @return the value of transform_order_details.payment_id
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    public String getPaymentId() {
        return paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transform_order_details.payment_id
     *
     * @param paymentId the value for transform_order_details.payment_id
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    public void setPaymentId(String paymentId) {
        this.paymentId = paymentId == null ? null : paymentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transform_order_details.order_status
     *
     * @return the value of transform_order_details.order_status
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transform_order_details.order_status
     *
     * @param orderStatus the value for transform_order_details.order_status
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transform_order_details.transform_amount
     *
     * @return the value of transform_order_details.transform_amount
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    public Integer getTransformAmount() {
        return transformAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transform_order_details.transform_amount
     *
     * @param transformAmount the value for transform_order_details.transform_amount
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    public void setTransformAmount(Integer transformAmount) {
        this.transformAmount = transformAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transform_order_details.order_subject
     *
     * @return the value of transform_order_details.order_subject
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    public String getOrderSubject() {
        return orderSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transform_order_details.order_subject
     *
     * @param orderSubject the value for transform_order_details.order_subject
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    public void setOrderSubject(String orderSubject) {
        this.orderSubject = orderSubject == null ? null : orderSubject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transform_order_details.create_time
     *
     * @return the value of transform_order_details.create_time
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transform_order_details.create_time
     *
     * @param createTime the value for transform_order_details.create_time
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transform_order_details.update_time
     *
     * @return the value of transform_order_details.update_time
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transform_order_details.update_time
     *
     * @param updateTime the value for transform_order_details.update_time
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transform_order_details.ali_name
     *
     * @return the value of transform_order_details.ali_name
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    public String getAliName() {
        return aliName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transform_order_details.ali_name
     *
     * @param aliName the value for transform_order_details.ali_name
     *
     * @mbggenerated Sun Oct 30 22:31:26 GMT+08:00 2022
     */
    public void setAliName(String aliName) {
        this.aliName = aliName == null ? null : aliName.trim();
    }
}