spring:
  application:
    name: order-server
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver   # mysql 驱动
      url: jdbc:mysql://123.57.39.124:3306/billing_system  # 连接数据库
      username: root    # 数据库账户
      password: liuHao123.    # 数据库密码

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8600
eureka:
  instance:
    #    hostname: localhost
    hostname: 123.57.39.124
  client:
    # 是否当作客户端注册到服务端, 默认为true
    register-with-eureka: true
    # 是否从Eureka获取注册信息
    fetch-registry: true
    serviceUrl:
      # 设置与Eureka Server交互的地址, 多个地址可使用','分隔。
      defaultZone: http://123.57.39.124:8761/eureka/


logging:
  level:
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN

mybatis:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

